// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rb.owish.domain;

import com.rb.owish.domain.Wish;
import com.rb.owish.domain.WishDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WishDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WishDataOnDemand: @Component;
    
    private Random WishDataOnDemand.rnd = new SecureRandom();
    
    private List<Wish> WishDataOnDemand.data;
    
    public Wish WishDataOnDemand.getNewTransientWish(int index) {
        Wish obj = new Wish();
        setDescription(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void WishDataOnDemand.setDescription(Wish obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void WishDataOnDemand.setTitle(Wish obj, int index) {
        String title = "title_" + index;
        if (title.length() > 255) {
            title = title.substring(0, 255);
        }
        obj.setTitle(title);
    }
    
    public Wish WishDataOnDemand.getSpecificWish(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Wish obj = data.get(index);
        Long id = obj.getId();
        return Wish.findWish(id);
    }
    
    public Wish WishDataOnDemand.getRandomWish() {
        init();
        Wish obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Wish.findWish(id);
    }
    
    public boolean WishDataOnDemand.modifyWish(Wish obj) {
        return false;
    }
    
    public void WishDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Wish.findWishEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Wish' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Wish>();
        for (int i = 0; i < 10; i++) {
            Wish obj = getNewTransientWish(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
